### PR TITLE
Update swift-nonempty version in Cartfile

### PR DESCRIPTION
**Pull request by mateuszszklarek**

### CODE REVIEW

**Comment by stephencelis** [comment]
Good catch! Thanks for the PR 😄

**Comment by mateuszszklarek** [comment]
Nice, amazing response time! Thanks! ❤️

**Comment by mateuszszklarek** [comment]
Nice, amazing response time! Thanks! ❤️

**Comment by mateuszszklarek** [comment]
@stephencelis Can you add new release version on github?

**Pull request merged**
